language: groovy
dist: trusty
jdk:
- openjdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew clean && ./gradlew war"
deploy:
  provider: releases
  api_key:
    secure: r+lMS29rkjGRHaZyaoLd9Ree+uGduLfELmJINmAVjssmzswo6u4sLOtPL7gGmrcX8dpiTtCZhe7J2gbile2sm1AOUrlE7Or7dxG8ZMn2ymD4VBZElwNsJIeAmFwy34EIyIQ4I5dH1G7nJwIaMwuzd3bUMJhsYp+Y4ypB5ITvbvtiYEllo5S76KC2xGUGFgVP1XTPgYicBZ1MgW/OfHCI24vBi6YH1PL30yijDGuMkXqTdkuLBBkdLm7GEhnH3LZbMXI7PKQ6se0MjMVepvMWAo/SSQTwl0/jto2o1el6esGxdnYB1/pp0smt5LY7HkABnyrERsi7zd5apRkzHYDBoIdEYzNDJx0L5617g5SQ8pfeThpBIN1bF2Vw1i66mc1Rcqquf0NH4DCPrw7vaqKsE8eaWgSVIV1tiIFTQAWW54o9cY+j7GLhOsOApr3VDirAid08BWYEBgCB84a8sZMcRuo7wnv3H5Iwkw+npUTi9+wyMMnQ+G8vdREiw7Q9LlBuGpvS4Gv17vB5LDj5WtVPYPMHQmQeLzagcDZWHgIjPkGodPVt4tmpVtJ9MGmXjm39KEXVNItRjgUni7WwpADlxi79J5og536RiG3nNMAEEOq6uXfO94yx8htvyBilXMJRFn2Jkn7aHn9uRtrZt8ovV9tcnqHCNaohPaFkw0Sz6RM=
  file_glob: 'true'
  skip_cleanup: 'true'
  overwrite: 'true'
  file: "build/libs/webapi-*.war"
  on:
    repo: bioatlas/webapi
    all-branches: true
    tags: true
